# -fno-rtti 
# -fno-exceptions
# -x c++
IF(NOT DEFINED ARDUINO_UPLOAD_METHOD)
    SET(ARDUINO_UPLOAD_METHOD "DFUUpload")
ENDIF(NOT DEFINED ARDUINO_UPLOAD_METHOD)

 #-D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__   -c -w -Os -g -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -MMD -ffunction-sections -fdata-sections -fno-exceptions -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0   -DARDUINO=10805 -DARDUINO_ESP8266_GENERIC -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_GENERIC" -DLED_BUILTIN=2 -DFLASHMODE_DOUT  -DESP8266 "

SET(ARDUINO_DEFAULT_CFLAGS " -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__    -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4   -w -Os -g  -ffunction-sections -fdata-sections -fno-exceptions ")
SET(ARDUINO_DEFAULT_CFLAGS " ${ARDUINO_DEFAULT_CFLAGS}   -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0   -DARDUINO=10805 -DARDUINO_ESP8266_GENERIC -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD=\"ESP8266_GENERIC\" -DLED_BUILTIN=2 -DFLASHMODE_DOUT  -DESP8266    ")
# FIXME : This is actually a linker flag !
SET(ARDUINO_DEFAULT_CFLAGS " ${ARDUINO_DEFAULT_CFLAGS}    -L${PLATFORM_PATH}/tools/sdk/lib ")

SET(ARDUINO_DEFAULT_CXXFLAGS "${ARDUINO_DEFAULT_CFLAGS} -fno-rtti  -fno-exceptions -std=c++11 ")
SET(ARDUINO_DEFAULT_CFLAGS "${ARDUINO_DEFAULT_CFLAGS} -std=gnu11")
